version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: ${DB_USERS_USERNAME}
      POSTGRES_PASSWORD: ${DB_USERS_PASSWORD}
    ports:
      - "5432:5432"